{% set version = "2.2.3" %}

package:
  name: deeplabcut
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/deeplabcut/deeplabcut-{{ version }}.tar.gz
  sha256: 13c1df41c24015a302425cde4b0d3d9fa97fc0fe7e0b45efc82ae66398b29cbf
  patches:
    - patches/0001-Do-not-install-download-script.patch
    - patches/0002-Silence-warnigns-about-tensorflow-lite.patch
    - patches/0003-Do-not-modify-tensorflow-warnings.patch


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  # Confirm with upstream before making this entry point
  # https://github.com/DeepLabCut/DeepLabCut/pull/1547
  entry_points:
    - dlc = deeplabcut.cli:main
    - deeplabcut = deeplabcut:launch_dlc

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - filterpy >=1.4.4
    - ruamel.yaml >=0.15.0
    - imgaug >=0.4.0
    - numba >=0.54
    - matplotlib-base >=3.3
    - networkx >=2.6
    - numpy >=1.18.5
    - opencv
    - pandas >=1.0.1,!=1.5.0
    - scikit-image >=0.17
    - scikit-learn >=1.0
    - scipy >=1.4
    - statsmodels >=0.11
    - pytables >=3.7.0
    - tensorflow >=2.0
    - tensorpack >=0.11
    - tf_slim >=1.1.0
    - tqdm
    - pyyaml
    - pillow >=7.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - deeplabcut
  # Confirm with upstream before making this entry point
  # https://github.com/DeepLabCut/DeepLabCut/pull/1547
  # commands:
  #   - dlc --help

about:
  home: www.deeplabcut.org
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: DeepLabCut is a toolbox for markerless pose estimation of animals performing various tasks.
  dev_url: https://github.com/DeepLabCut/DeepLabCut

extra:
  recipe-maintainers:
    - hmaarrfk
